server:
  port: 8081                            # Server will run on http://localhost:8081
  servlet:
    context-path: /myapp               # Application will be accessible at /myapp

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_media  # Correct JDBC URL
    username: subhash                              # DB username
    password: Ab@128900                             # DB password
    driver-class-name: com.mysql.cj.jdbc.Driver     # MySQL JDBC Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update                # Auto-creates or updates DB tables
    show-sql: true                   # Logs SQL statements in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect #Tells Hibernate to use MySQL-specific syntax
jwt:
  secret: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V
  expiration: 3600000